#!/bin/bash
# mkfont.sh — turn the kernel's VGA 8x16 console font into a C header for
# eink213v4.c, so the e-Paper tool can draw text without any font library.
#
# Usage: mkfont.sh [kernel-source-dir] [output-header]
# Defaults: ../../src/linux-stable_20231123 and ./font8x16.h
#
# Source: lib/fonts/font_8x16.c (GPL-2.0, the classic IBM VGA ROM bitmap).
# 256 glyphs x 16 rows x 1 byte = 4096 bytes, bit 7 = leftmost pixel.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
KSRC="${1:-${HERE}/../../src/linux-stable_20231123}"
OUT="${2:-${HERE}/font8x16.h}"
SRC="${KSRC}/lib/fonts/font_8x16.c"

[[ -f ${SRC} ]] || { echo "❌  No ${SRC} — pass a kernel source dir" >&2; exit 1; }

# the struct header line ('{ 0, 0, FONTDATAMAX, 0 }') carries no hex, so
# everything from it on is glyph data — but each glyph starts with a comment
# like /* 0 0x00 '^@' */, whose hex would otherwise be counted as data
bytes=$(sed -n '/FONTDATAMAX, 0 }/,$p' "${SRC}" | sed 's|/\*.*\*/||' |
        grep -o '0x[0-9a-fA-F]\{2\}')
n=$(echo "${bytes}" | wc -l)
[[ ${n} -eq 4096 ]] || { echo "❌  Extracted ${n} bytes, expected 4096" >&2; exit 1; }

{
    echo "/* Generated by rpi/mkfont.sh from ${SRC#"${HERE}"/} — do not edit."
    echo "   Kernel VGA 8x16 console font (GPL-2.0), 256 glyphs, MSB = left. */"
    echo "#define FONT_W 8"
    echo "#define FONT_H 16"
    echo "static const unsigned char font8x16[4096] = {"
    echo "${bytes}" | awk '{printf "%s,%s", $0, (NR%12==0 ? "\n" : " ")} END{print ""}' |
        sed 's/^/    /'
    echo "};"
} > "${OUT}"

echo ">>>  Wrote ${OUT} (${n} bytes of glyph data)"
